version: '2'
services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    network_mode: "host"
    volumes:
      - ./nginx/conf:/etc/nginx/conf.d/
      - ./nginx/log/:/var/log/nginx/
    restart: always
    privileged: true
  dockerui:
    image: portainer/portainer:latest
    container_name: portainer
    networks:
      - default
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./portainer/data:/data
    command: -H unix:///var/run/docker.sock
    restart: always
    privileged: true
networks:
  default:
    external:
      name: base
