version: '2'

services:
  db:
    image: mariadb:latest
    container_name: mysql
    volumes:
      - ./mysql/mariadb10/data:/var/lib/mysql
      - ./mysql/mariadb10/data:/var/log/mysql
      - ./mysql/mariadb10/conf:/etc/mysql/conf.d
    networks:
      - default
    ports:
      - "3306:3306"
    env_file:
      - ./mysql/mariadb10/conf/mysql.env
    restart: always
    privileged: true
  web:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    networks:
      - default
    ports:
      - "43580:80"
    volumes:
      - ./phpmyadmin/theme:/www/themes/mytheme
    restart: always
    env_file:
      - ./phpmyadmin/conf/phpmyadmin.env
    privileged: true

networks:
  default:
    external:
      name: pub_db
