version: '2'
services:
  php:
    image: armhf/php
    container_name: php
    networks:
      - default
    volumes:
      - ./php/www:/www
    restart: always
    privileged: true
networks:
  default:
    external:
      name: base
