version: '2'
services:
  php:
    image: armhf/php
    container_name: php
    networks:
      - default
    ports:
      - "9100:9000"
    volumes:
      - ./php/www:/var/www/html
    restart: always
    privileged: true
networks:
  default:
    external:
      name: base
