version: "2.0"

services:
  ss:
    image: teddysun/shadowsocks-libev:alpine
    container_name: shadowsocks
    networks:
      - pub_vpn
    restart: always
    ports:
      - "7703:7703"
    volumes:
      - ./shadowsocks/conf:/etc/shadowsocks-libev
  ssr:
    image: teddysun/shadowsocks-r:alpine 
    container_name: shadowsocks-r
    networks:
      - pub_vpn
    restart: always
    ports:
      - "7706:7706"
    volumes:
      - ./shadowsocks-r/conf:/etc/shadowsocks-r
  l2tp:
    image: teddysun/l2tp:alpine 
    container_name: l2tp
    networks:
      - pub_vpn
    restart: always
    ports:
      - "500:500/udp"
      - "4500:4500/udp"
      - "1701:1701"
    volumes:
      - ./l2tp/modules:/lib/modules
    env_file:
      - ./l2tp/conf/l2tp.env
    privileged: true
      
networks:
  pub_vpn:
    external:
      name: pub_vpn
